import '../pages/globals.css'
import Layout from '../components/layout'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function MyApp({ Component, pageProps }: { Component: React.JSX.ElementType, pageProps: any }) {
  return (
    <Layout>
      <Component {...pageProps} />
    </Layout>
  )
}